FROM python:3.10.5-bullseye


RUN apt-get update -y

# RUN pip install --upgrade pip setuptools wheel # to get latest setuptools
RUN pip install --upgrade pip wheel
RUN pip install setuptools

# Set the default directory where CMD will execute
RUN mkdir -p /var/task
RUN mkdir -p /var/data
WORKDIR /var/task

ENV PYTHONPATH "/var/task/:$PYTHONPATH"

ADD requirements.txt /var/task

RUN pip install -r requirements.txt

ENTRYPOINT ["pytest", "-rP", "chess/tests.py"]